name: ialarm-mqtt (development)
url: https://github.com/maxill1/addons/tree/master/ialarm-mqtt
version: dev-5e82642
slug: ialarm-mqtt-dev
description: integrates iAlarm (antifurtocasa365, Emooluxr, Casasicura and other Meian/Focus clones) via node-ialarm library
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: application
boot: auto
options:
  verbose: false
  server:
    host: 192.168.1.81
    port: 18034
    username: admin
    password: password
    zones:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
    showUnnamedZones: true
    areas: 1
    delay: 200
    features:
      - armDisarm
      - sensors
      - events
      - bypass
      - zoneNames
    polling_status: 5000
  mqtt:
    host: 192.168.1.82
    port: 1883
    username: admin
    password: password
    clientId: ialarm-mqtt
    cache: 5m
    retain: true
  hadiscovery:
    alarm_qos: 2
    sensors_qos: 0
    zoneName: Zone
  events:
    name: last event
    icon: mdi:message-alert
  bypass:
    name: Bypass
    icon: mdi:lock-open
  zones: []
schema:
  verbose: bool
  name: str?
  server:
    host: str
    port: int
    username: str
    password: password
    zones:
      - int(1,128)
    showUnnamedZones: bool
    areas: list(1|2|3|4)
    delay: int
    features:
      - list(armDisarm|sensors|events|bypass|zoneNames)
    polling_status: int
  mqtt:
    host: str
    port: int
    username: str
    password: password
    clientId: str?
    cache: str
    retain: bool
  hadiscovery:
    sensors_qos: list(0|1|2)
    alarm_qos: list(0|1|2)
    code: match(^\d{4}$)?
    zoneName: str
  events:
    name: str
    icon: match(mdi:\w*)
  bypass:
    name: str
    icon: match(mdi:\w*)
  zones:
    - number: int
      contactType: list(NO|NC)?
      device_class: str?
      statusProperty: list(alarm|open|fault|ok|problem|lowbat)?
image: maxill1/{arch}-addon-ialarm-mqtt-dev
